### PR TITLE
Fixes #66, #68 and #69

### LINKED ISSUE #66: Dots on AICc
Dears, AICc manual inform that this method compute auxiliary information, but when I inform other parameter (base, logLik. delta, weights) to show on table occur a error:
```r
data(moths)
modls <- fitls(moths)
modln <- fitlnorm(moths)
AICc(modls, modln, weights=TRUE)
```

```
Error in AICc(modls, modln, nobs = length(moths), base = TRUE) : 
  all objects in list must be class mle2 or inherit from mle2
```
In source of method, dots are models and parameter concatenated:

```r
L <- list(object, ...)
```

Then, when check `L` occur the error:

```r
if (!all(sapply(L, function(x) inherits(x, "mle2")))) 
    stop("all objects in list must be class mle2 or inherit from mle2")
```

It is better to inform on manual if dots can be used to set parameter or only models.

Best regards,

Mario

### LINKED ISSUE #68: Inconsistent calls between fitgeom and fitsad
Calls to `fitsad` introduce truncation for some distributions; however the calls to the underlying `fitgeom`, etc, do not. This makes fits with `fitsad(..., sad="geom")` inconsistent with `fitgeom(...)`: 

```R
> fitgeom(moths)
Maximum likelihood estimation
Type: discrete species abundance distribution
Species: 240 individuals: 15609 
Call:
mle2(minuslogl = function (prob) 
-sum(dgeom(x, prob, log = TRUE)), start = list(prob = 0.0151429112246829), 
    method = "Brent", data = list(x = list(1, 1, 1, 1, 1, "etc")), 
    lower = 0, upper = 1)
Coefficients:
      prob 
0.01514291 
Log-likelihood: -1243.83 



> fitsad(moths, sad="geom")
Maximum likelihood estimation
Type: discrete species abundance distribution
Species: 240 individuals: 15609 
Call:
mle2(minuslogl = function (prob) 
-sum(dtrunc("geom", x = x, coef = prob, trunc = trunc, log = TRUE)), 
    start = list(prob = 0.0151429112246829), method = "Brent", 
    data = list(x = list(1, 1, 1, 1, 1, "etc")), lower = 0, upper = 1)
Coefficients:
prob 
   1 
Truncation point: 0 
Log-likelihood: -Inf 
```

### PR DESCRIPTION
**Pull request by andrechalom**
I've tested the code for fixing #68 and #69, and they work as expected. Added a `suppressWarnings` to dmzsm in order to suppress a warning that was being thrown when x > J, even though the end result was correctly displayed as zero.

### CODE REVIEW

**Comment by piklprado** [comment]
Do you think we should merge this to master before releasing the next version in CRAN? I supposed that we'll use master to keep the last release only. But maybe I am missing some advantage to add fixes to the master as we do them.

**Comment by andrechalom** [comment]
I'd recommend merging this to master and releasing it on CRAN, as we have
fixed several important bugs since our last release in June. I'm trying to
fix #66 as well, but I'm getting really lost with S4 method dispatching...

**Comment by piklprado** [comment]
Before merging we might check if for other distributions that have a maximum we have the same issue as #69

**Comment by andrechalom** [comment]
Fixed #69 for dvolkov. Should update the NEWS file before submitting to CRAN.

**Pull request merged**
